# Generated by Django 5.0.2 on 2024-02-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("TaskCategory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="taskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskTitle", models.CharField(max_length=255)),
                ("taskDescription", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
                ("taskAssignDate", models.DateField()),
                ("categories", models.ManyToManyField(to="TaskCategory.category")),
            ],
        ),
    ]
