# Generated by Django 5.0.2 on 2024-02-21 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TaskModel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmodel",
            name="taskAssignDate",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
